/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      fontFamily: {
        "Noto-Sans": ["Noto Sans"],
        "Roboto-Slab": ["Roboto Slab"],
      },
      colors: {
        "btn-bg-color": "#00368C",
        yellowbg: "#FFC701",
        "gray-border": "#F0F0F0",
        graybg: "#EBEBEB",
        homeblue: "#009DC4",
        homeblue2: "#0279A0",
        whatsAppbg: "#30CC45",
        linkedInbg: "#007AB9",
        twitterbg: "#007AB9",
        facebookbg: "#3A589B",
        grayborder: "#B1B1B1",
        f4feff: "#F4FEFF",
        c2e9ed: "#C2E9ED",
        blurbg: "rgba(0, 0, 0, 0.5)",
        blurborder: "rgba(0,0,0,0.2)",
        ffc701: "#ffc701",
        lightyellow: "#FFEEB3",
        "filter-color": "#F5F5F5",
        "light-yellow": "#fff9f4",
        grey: "#F5F5F5",
        "btn-bg-color": "#00368C",
        "btn-bg-color2": "#032863",
        "00368c": "#00368C",
        yellowbg: "#FFC701",
        "gray-border": "#F0F0F0",
        homeblue: "#009DC4",
        whatsAppbg: "#30CC45",
        linkedInbg: "#007AB9",
        twitterbg: "#007AB9",
        facebookbg: "#3A589B",
        grayborder: "#B1B1B1",
        f4feff: "#F4FEFF",
        c2e9ed: "#C2E9ED",
        blurbg: "rgba(0, 0, 0, 0.5)",
        blurborder: "rgba(0,0,0,0.2)",
        pinkredbg: "#FFF9F4",
        lightpink: "#FFF5F4",
        darkgreen: "#4EB158",
        ffc701: "#ffc701",
        lightyellow: "#FFEEB3",
        "filter-color": "#F5F5F5",
        "light-yellow": "#fff9f4",
        grey: "#F5F5F5",
        darkblue: "#00368C",
        fadedyellow: "#FFFAE7",
        viewall: "#1718F11A",
      },
      boxShadow: {
        "3xl": "0 0 20px 6px rgba(0, 0, 0, 0.05)",
        "4xl": "0px 0px 6px 2px rgba(0, 0, 0, 0.06)",
        "5xl": "0px 0px 6px 2px rgba(0, 0, 0, 0.1)",
        "6xl": "0px 0px 10px 4px rgba(0,0,0,0.06)",
        "7xl": "0px 0px 10px 4px rgba(0,0,0,0.1)",
      },
      backgroundImage: {
        "gradient-radial": "radial-gradient(var(--tw-gradient-stops))",
        "gradient-conic":
          "conic-gradient(from 180deg at 50% 50%, var(--tw-gradient-stops))",
        bgRectangle: "url('/images/bgRectangle.png')",
        "gradient-conic":
          "conic-gradient(from 180deg at 50% 50%, var(--tw-gradient-stops))",
        bgRectangle: "url('/images/bgRectangle.png')",
        ellipse1: "url('/home/Ellipse 203.png')",
        whoweare: "url('/images/whoweare-background.png')",
        menuBg: "url('/images/menuBg.png')",
      },
      fontSize: {
        "heading-font": "2.5rem",
        xl: "19px",
      },
      width: {
        "heading-width": "32.75",
        aboutcard: "309px",
        mobile: "200px",
      },
      lineHeight: {
        heading: "3.3125rem",
      },
      spacing: {
        587: "24rem",
      },
    },
  },
  plugins: [],
};
