const data = [
  {
    title: "Empower children from low-income communities to build...",
    by: "Youth with a mission",
    image: "/donate/donate01.png",
    requiredAmount: 75000,
    raisedAmount:80000,
    goalAmount:100000,
    investedAmount: 50000,
    ramainingdays: "2",
    investors: "84",
  },
  {
    title: "Lorem ipsum dolor sit amet, consectetur adipiscing elit...",
    by: "Youth with a mission",
    image: "/donate/donate02.png",
    requiredAmount: 75000,
    raisedAmount:80000,
    goalAmount:100000,
    investedAmount: 50000,
    ramainingdays: "2",
    investors: "84",
  },
  {
    title: "Empower children from low-income communities to build...",
    by: "Youth with a mission",
    image: "/donate/donate03.png",
    requiredAmount: 75000,
    raisedAmount:80000,
    goalAmount:100000,
    investedAmount: 50000,
    ramainingdays: "2",
    investors: "84",
  },
  {
    title: "Lorem ipsum dolor sit.",
    by: "Youth with a mission",
    image: "/donate/donate04.png",
    requiredAmount: 75000,
    raisedAmount:80000,
    goalAmount:100000,
    investedAmount: 50000,
    ramainingdays: "2",
    investors: "84",
  },
  {
    title: "Lorem ipsum dolor sit amet, consectetur adipiscing elit...",
    by: "Youth with a mission",
    image: "/donate/donate05.png",
    requiredAmount: 75000,
    raisedAmount:80000,
    goalAmount:100000,
    investedAmount: 50000,
    ramainingdays: "2",
    investors: "84",
  },
  {
    title: "Offer A Helping Hand To Support Rubina Rodgers Treatment",
    by: "Youth with a mission",
    image: "/donate/donate06.png",
    requiredAmount: 75000,
    raisedAmount:80000,
    goalAmount:100000,
    investedAmount: 50000,
    ramainingdays: "2",
    investors: "84",
  },
  {
    title: "Lorem ipsum dolor sit amet, consectetur adipiscing elit...",
    by: "Youth with a mission",
    image: "/donate/donate07.png",
    requiredAmount: 75000,
    raisedAmount:80000,
    goalAmount:100000,
    investedAmount: 50000,
    ramainingdays: "2",
    investors: "84",
  },
  {
    title: "Lorem ipsum dolor sit amet, consectetur adipiscing elit...",
    by: "Youth with a mission",
    image: "/donate/donate08.png",
    requiredAmount: 75000,
    raisedAmount:80000,
    goalAmount:100000,
    investedAmount: 50000,
    ramainingdays: "2",
    investors: "84",
  },
  {
    title: "Lorem ipsum dolor sit amet, consectetur adipiscing elit...",
    by: "Youth with a mission",
    image: "/donate/donate09.png",
    requiredAmount: 75000,
    raisedAmount:80000,
    goalAmount:100000,
    investedAmount: 50000,
    ramainingdays: "2",
    investors: "84",
  },
  {
    title: "Offer A Helping Hand To Support Rubina Rodgers Treatment",
    by: "Youth with a mission",
    image: "/donate/donate01.png",
    requiredAmount: 75000,
    raisedAmount:80000,
    goalAmount:100000,
    investedAmount: 50000,
    ramainingdays: "2",
    investors: "84",
  },
  {
    title: "Offer A Helping Hand To Support Rubina Rodgers Treatment",
    by: "Youth with a mission",
    image: "/donate/donate02.png",
    requiredAmount: 75000,
    raisedAmount:80000,
    goalAmount:100000,
    investedAmount: 50000,
    ramainingdays: "2",
    investors: "84",
  },
  {
    title: "Offer A Helping Hand To Support Rubina Rodgers Treatment",
    by: "Youth with a mission",
    image: "/donate/donate02.png",
    requiredAmount: 75000,
    raisedAmount:80000,
    goalAmount:100000,
    investedAmount: 50000,
    ramainingdays: "2",
    investors: "84",
  },
  {
    title: "Offer A Helping Hand To Support Rubina Rodgers Treatment",
    by: "Youth with a mission",
    image: "/donate/donate03.png",
    requiredAmount: 75000,
    raisedAmount:80000,
    goalAmount:100000,
    investedAmount: 50000,
    ramainingdays: "2",
    investors: "84",
  },
  {
    title: "Offer A Helping Hand To Support Rubina Rodgers Treatment",
    by: "Youth with a mission",
    image: "/donate/donate04.png",
    requiredAmount: 75000,
    raisedAmount:80000,
    goalAmount:100000,
    investedAmount: 50000,
    ramainingdays: "2",
    investors: "84",
  },
];

export { data };
