const investData = [
  {
    title: "Suparna Gayen And Group",
    by: "Velicham Finance Private Limited",
    image: "/invest/invest01.png",
    requiredAmount: 100000,
    investedAmount: 50000,
    disbursed: "40,000",
    interestRate: "8.5",
    period: "12",
    investors: "84",
  },
  {
    title: "Suparna Gayen And Group",
    by: "Velicham Finance Private Limited",
    image: "/invest/invest02.png",
    requiredAmount: 100000,
    investedAmount: 50000,
    disbursed: "40,000",
    interestRate: "8.5",
    period: "12",

    investors: "84",
  },
  {
    title: "Suparna Gayen And Group",
    by: "Velicham Finance Private Limited",
    image: "/invest/invest03.png",
    requiredAmount: 100000,
    investedAmount: 50000,
    disbursed: "40,000",
    interestRate: "8.5",
    period: "12",
    investors: "84",
  },
  {
    title: "Suparna Gayen And Group",
    by: "Velicham Finance Private Limited",
    image: "/invest/invest04.png",
    requiredAmount: 100000,
    investedAmount: 50000,
    disbursed: "40,000",
    interestRate: "8.5",
    period: "12",
    investors: "84",
  },
  {
    title: "Suparna Gayen And Group",
    by: "Velicham Finance Private Limited",
    image: "/invest/invest05.png",
    requiredAmount: 100000,
    investedAmount: 50000,
    disbursed: "40,000",
    interestRate: "8.5",
    period: "12",
    investors: "84",
  },
  {
    title: "Suparna Gayen And Group",
    by: "Velicham Finance Private Limited",
    image: "/invest/invest06.png",
    requiredAmount: 100000,
    investedAmount: 50000,
    disbursed: "40,000",
    interestRate: "8.5",
    period: "12",
    investors: "84",
  },
  {
    title: "Suparna Gayen And Group",
    by: "Velicham Finance Private Limited",
    image: "/invest/invest07.png",
    requiredAmount: 100000,
    investedAmount: 50000,
    disbursed: "40,000",
    interestRate: "8.5",
    period: "12",
    investors: "84",
  },
  {
    title: "Suparna Gayen And Group",
    by: "Velicham Finance Private Limited",
    image: "/invest/invest08.png",
    requiredAmount: 100000,
    investedAmount: 50000,
    disbursed: "40,000",
    interestRate: "8.5",
    period: "12",
    investors: "84",
  },
  {
    title: "Suparna Gayen And Group",
    by: "Velicham Finance Private Limited",
    image: "/invest/invest09.png",
    requiredAmount: 100000,
    investedAmount: 50000,
    disbursed: "40,000",
    interestRate: "8.5",
    period: "12",
    investors: "84",
  },

  {
    title: "Suparna Gayen And Group",
    by: "Velicham Finance Private Limited",
    image: "/invest/invest09.png",
    requiredAmount: 100000,
    investedAmount: 50000,
    disbursed: "40,000",
    interestRate: "8.5",
    period: "12",
    investors: "84",
  },
  {
    title: "Suparna Gayen And Group",
    by: "Velicham Finance Private Limited",
    image: "/invest/invest08.png",
    requiredAmount: 100000,
    investedAmount: 50000,
    disbursed: "40,000",
    interestRate: "8.5",
    period: "12",
    investors: "84",
  },
  {
    title: "Suparna Gayen And Group",
    by: "Velicham Finance Private Limited",
    image: "/invest/invest07.png",
    requiredAmount: 100000,
    investedAmount: 50000,
    disbursed: "40,000",
    interestRate: "8.5",
    period: "12",
    investors: "84",
  },
  {
    title: "Suparna Gayen And Group",
    by: "Velicham Finance Private Limited",
    image: "/invest/invest06.png",
    requiredAmount: 100000,
    investedAmount: 50000,
    disbursed: "40,000",
    interestRate: "8.5",
    period: "12",
    investors: "84",
  },

  {
    title: "Suparna Gayen And Group",
    by: "Velicham Finance Private Limited",
    image: "/invest/invest05.png",
    requiredAmount: 100000,
    investedAmount: 50000,
    disbursed: "40,000",
    interestRate: "8.5",
    period: "12",
    investors: "84",
  },
  {
    title: "Suparna Gayen And Group",
    by: "Velicham Finance Private Limited",
    image: "/invest/invest04.png",
    requiredAmount: 100000,
    investedAmount: 50000,
    disbursed: "40,000",
    interestRate: "8.5",
    period: "12",
    investors: "84",
  },
  {
    title: "Suparna Gayen And Group",
    by: "Velicham Finance Private Limited",
    image: "/invest/invest03.png",
    requiredAmount: 100000,
    investedAmount: 50000,
    disbursed: "40,000",
    interestRate: "8.5",
    period: "12",
    investors: "84",
  },
  {
    title: "Suparna Gayen And Group",
    by: "Velicham Finance Private Limited",
    image: "/invest/invest02.png",
    requiredAmount: 100000,
    investedAmount: 50000,
    disbursed: "40,000",
    interestRate: "8.5",
    period: "12",
    investors: "84",
  },
  {
    title: "Suparna Gayen And Group",
    by: "Velicham Finance Private Limited",
    image: "/invest/invest01.png",
    requiredAmount: 100000,
    investedAmount: 50000,
    disbursed: "40,000",
    interestRate: "8.5",
    period: "12",
    investors: "84",
  },
];

export { investData };
